// Edit this file to change page copy and remote image, audio, and GIF URLs.
export const siteContent = {
  girlfriendName: "Dek Aliya",
  entryQuestion: "Apakah kamu mengakui kalo Dek Aliya sudah berusaha dengan sangat keras selama ini dan usahanya patut dihargai?",
  gate: {
    eyebrow: "A little question before we begin",
    note: "You deserve to hear it: every bit of effort you give matters.",
    yesButton: "YES! Pasti dong",
    noButton: "NO",
    noTips: ["Eits gabisa!", "Gaboleh nolak!", "Tombol ini rusak~", "Coba lagi deh~"],
    footer: "A birthday gift · made with love",
  },
  header: {
    homeHref: "#top",
    brandLineOne: "OUR LITTLE",
    brandLineTwo: "ARCHIVE",
    issue: "ISSUE NO. 01",
    edition: "BIRTHDAY EDITION",
    links: [
      { label: "Our story", href: "#memories" },
      { label: "Little things", href: "#little-things" },
      { label: "A letter", href: "#letter" },
    ],
  },
  hero: {
    eyebrow: "26th September 2026",
    title: "Happy birthday!",
    intro: "Thank you for being the most wonderful person in my life. I hope your days with me are filled with as much joy and love as you bring to everyone around you.",
    link: "Turn the first page",
    memoriesHref: "#memories",
    indexNumber: "01",
    index: "THE STORY SO FAR",
    imageCaption: "the day everything got brighter",
    note: "for my favorite person",
    scribble: "our kind of magic",
    imageUrl: "/images/hero.jpeg",
  },
  memoriesSection: {
    number: "01",
    eyebrow: "Our little moments",
    title: "A few photos to remember",
    description: "Let's take a walk down memory lane, and relive some of our favorite moments together.",
  },
  memories: [
    { title: "The First Time We Met", tag: "FIRST MEETING", date: "—", caption: "Pertama kali aku ketemu kamu aku ga ngira kita akan tetep ngomong sampe sekarang. Aku kira ah ini mah nanti juga orangnya bakal lupa aku. Makanya waktu pertama kali ketemu, aku ga terlalu inget wajah kamu. Tapi ternyata aku salah. Kamu ternyata masih ada di sini dan aku tetep mikirin kamu meskipun kkn nya udah beres. Tapi dulu aku lihat kamu kayak yang reliable banget.", imageUrl: "/images/meet.jpeg", alt: "Two people smiling together" },
    { title: "The First Time We Held Hands", tag: "LITTLE MOMENT", date: "—", caption: "Momen yang paling aku sukai di pangandaran. Tau ga selama di pangandaran itu aku masih belum bisa tenang? Biasanya kalo udah beres sesuatu itu aku biasanya bisa nyantai terus mikirin habis KKN mau apa. Tapi pas di pangandaran aku terus mikirin kamu. Aku harus ngelakuin sesuatu biar abis ini aku masih punya alasan ketemu kamu. Aku ga mau asing sama kamu. Makanya aku confess pas sunset itu meskipun aku masih ragu. Pertama kali pegang tangan kamu aku udah mulai yakin kalo aku harus temenin kamu bagaimanapun keadaannya.", imageUrl: "/images/hands.jpg", alt: "A couple holding hands" },
    { title: "The First Time We Went Out Together", tag: "FIRST DATE?", date: "—", caption: "Pertama kalinya kita pergi ke suatu tempat berdua. Meskipun ga lama, tapi rasanya seru banget dan aku juga harap kamu ngerasain hal yang sama. Pengennya sih jalan lebih lama lagi, tapi kan kos kamu tutup jam 10 jadinya ga bisa lama-lama. Kita juga diusir sama penjaga lapang dadaha jadinya mau ga mau harus pulang wkwkwkwk.", imageUrl: "/images/date.jpeg", alt: "A cozy table set for two" },
    { title: "The Day We Officially Became a Couple", tag: "MILESTONE", date: "—", caption: "Jarak aku confess dan kita jadian itu agak jauh. Malah aku cari momen pas biar nanti kita annivnya ga keteteran harus ngurusin hal yang lain. Makanya aku kira hari ulang tahun aku jadiin tanggal jadian aja biar ngerayain anniversary bisa sambil ngerayain ulang tahun. Tapi dulu agak khawatir juga kalo kamu mulai bosen sama aku. Makanya aku sempet tanya Bayu apa kita udah kelamaan jadi HTS. Bayu sempet bilang aku harus cepet submit karya takut kelewat deadline. Trauma dikar sama spotyfest aku langsung muncul abis itu karena hubungan kita disamain sama karya pameran wkwkwk.", imageUrl: "/images/official.jpeg", alt: "A couple sharing a happy moment" },
    { title: "My Absolute Favorite Photo of You", tag: "FAVORITE", date: "—", caption: "Foto ini selalu bikin aku senyum sendiri tiap lihat. Foto ini bukan hanya foto portrait terbagus yang pernah aku ambil dengan close up high angle dengan sedikit memanfaatkan komposisi diagonal terus cahaya warm dari-... oke bahas fotonya lain kali aja. Tapi selain itu kita juga spending time agak lama juga hari itu. Ngobrol banyak tentang banyak hal dan juga kita coba photobooth lagi kedua kalinya after di Gula Padi.", imageUrl: "/images/fav.jpeg", alt: "A joyful portrait" },
  ],
  telemetry: {
    eyebrow: "A totally accurate data",
    title: "Relationship Dashboard",
    status: "LIVE — all systems synced with love",
    stats: [
      { value: "999.999%", label: "Love Level", note: "Overclocked" },
      { value: "100%", label: "Miss Meter (Kangen)", note: "Continuous Sync" },
    ],
    counters: [
      { value: "999999999 times", label: "Times you made my day" },
      { value: "999999999 times", label: "Times I think about you" },
      { value: "999999999 times", label: "Times you punched me" },
      { value: "0 times", label: "Times I ignored you (lol)" },
      { value: "999999999 times", label: "Times you were right" },
      { value: "0 times", label: "Times I was right" },
      { value: "999999999 times", label: "Times you mentioned Jeonghan, Haechan and other korean men" },
      { value: "0 times", label: "Times I mentioned Kikuri" },
    ],
  },
  littleThingsSection: {
    number: "02",
    eyebrow: "The details I keep noticing",
    title: "Little things, big love",
    description: "Six tiny reasons I fall for you, on repeat.",
    noteLabel: "NOTE",
    notes: [
      { emoji: "😄", title: "Your 'Salting Moment'", description: "The way you punched me while salting is so cute!" },
      { emoji: "😤", title: "Your Reaction", description: "Mungkin aku ga setengil dulu, tapi aku suka banget reaksi kamu kalo aku usilin" },
      { emoji: "🤩", title: "Yap, yap and yap", description: "Keliatannya aku ga suka karena aku kebanyakan diem, tapi aku suka banget kalo kamu cerita ke aku. Malah aku bisa lebih terbuka ke kamu gara-gara itu" },
      { emoji: "✨", title: "Your kindness", description: "You always trying to do good to others. Even trying to understand me even though i keep avoiding you when things get hard." },
      { emoji: "🔥", title: "Your Determination", description: "Your unwavering commitment to your goals is the most beautiful thing you have and i hope nothing can took that away from you." },
      { emoji: "💬", title: "Texts from you", description: "Chat kamu meskipun aku sering kewalahan buat balesnya karena buanyakkk banget, tapi setiap liat notif dari kamu bisa bikin aku bahagia." },
    ],
  },
  soundtrack: {
    eyebrow: "Side A · our soundtrack",
    heading: "A little song",
    subheading: "for your day.",
    description: "I don't listen to love song that much. Aku rasa emosi manusia itu bukan cuma cinta doang, emosi manusia terlalu luas untuk dieksplor buat dijadiin karya. Tapi mungkin satu lagi ini sering ngingetin aku ke kamu. Sisanya ya kayaknya ga ada lagu yang ingetin aku ke kamu, soalnya kebanyakan lagu aku soal isu sosial, depresi, suicidal, dan kucing yang bisa ngudud.",
    title: "Blossom",
    artist: "Porter Robinson",
    mixLabel: "BIRTHDAY MIX · 01",
    artworkUrl: "/images/nurture.png",
    audioUrl: "/images/song.mp3",
    errorMessage: "Couldn't load the track. Check your connection.",
  },
  loveLetter: {
    eyebrow: "03 · A NOTE FOR YOU",
    title: "To the girl who tries so hard,",
    paragraphs: [
      "I just want you to know that I see how hard you've been working, for us, for yourself, for everyone around you. It doesn't go unnoticed, even on the days you think it does. Meskipun dunia ga ngasih reward yang sepadan dengan usaha kamu. Aku harap kamu ga pernah berhenti untuk menjadi versi kamu yang terbaik. ",
      "Things might go wrong or even feel unfair. Ga ada salahnya kok kamu istirahat dulu sejenak, meluapkan keluh kesah kamu ke aku atau pun ke siapapun, atau bahkan cuma goresan pena sekalipun. Tapi aku liat usaha kamu kok. Aku liat seberapa keras kamu udah berusaha dan kamu harus apresiai itu. Jangan terlalu keras ke diri kamu sendiiri yaa. Kita bisa kok hadepin semuanya bersama.",
      "We might have our own problems. Kamu sibuk dengan urusan kamu, dan aku sibuk dengan urusan aku sendiri. Tapi aku selalu ada buat kamu. Aku selalu dengerin keluh kesah kamu. Aku minta maaf sebesar-besarnya karena aku udah jarang hubungin kamu. Tapi aku tetep peduli sama kamu kok apapun yang terjadi. You're not alone in this.",
      "Di ulang tahun kamu hari ini, aku harap semuanya akan menjadi lebih mudah buat kamu. Aku harap semua doa kamu yang telah kamu panjatkan akan terkabul. Aku harap kamu juga akan diberi kesehatan dan kebahaagiaan selalu. Aku sayang kamu dan ga ada yang bisa rubah perasaan itu. You're the most beautiful person in my life, and I hope you always remember that.",
    ],
    signOff: "With all my love, always yours.",
    signature: "— Febrian,",
    stampTop: "WITH",
    stampBottom: "LOVE",
  },
  surprise: {
    eyebrow: "One last little thing",
    button: "A little surprise",
    countdownPrefix: "will appear on your location in",
    modalEyebrow: "Something sweet is on its way",
    resultEyebrow: "A tiny plot twist",
    resultMessage: "Too bad, you should wait a little bit longer :(",
    closeLink: "Back to the scrapbook",
    gifUrl: "https://media.giphy.com/media/3oz8xIsloV7zOmt81G/giphy.gif",
  },
  accessibility: {
    home: "Birthday scrapbook home",
    backToTop: "Back to the top",
    playMusic: "Play music",
    pauseMusic: "Pause music",
    progress: "Music progress",
    closeSurprise: "Close surprise",
    noButton: "No, moves away",
    surprise: "Birthday surprise",
  },
  footer: {
    madeFor: "Made for",
    signoff: "with all my heart.",
    finalNote: "KEEP THIS PAGE",
    backToTopHref: "#top",
  },
};
